# prometheus-values.yaml
alertmanager:
  enabled: false

prometheus-pushgateway:
  enabled: false

kube-state-metrics:
  enabled: false

prometheus-node-exporter:
  enabled: false

server:
  persistentVolume:
    size: 2Gi
  # Reduce resource usage for local/dev
  resources:
    requests:
      memory: 128Mi
      cpu: 100m
    limits:
      memory: 256Mi
      cpu: 200m

  # Create a ServiceMonitor so Prometheus Operator (if used) can discover
  # Otherwise, use `additionalScrapeConfigs`
  service:
    type: LoadBalancer

  # Enable scraping custom targets
extraScrapeConfigs: |
  - job_name: '${APPLICATION_NAME}'
    metrics_path: /metrics
    static_configs:
      - targets:
        - ${APPLICATION_NAME}-service.${APPLICATION_NAMESPACE}.svc.cluster.local:8000
