apiVersion: v1
kind: Namespace
metadata:
  name: prod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit
  namespace: prod
  labels:
    app: streamlit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      containers:
        - name: streamlit
          image: onoureldin14/streamlit-app:latest
          ports:
            - containerPort: 8501
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: streamlit-service
  namespace: prod
spec:
  selector:
    app: streamlit
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8501
