apiVersion: v1
kind: Namespace
metadata:
  name: prod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit
  namespace: prod
  labels:
    app: streamlit
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: "8000"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      containers:
        - name: streamlit
          image: onoureldin14/streamlit-app:latest
          ports:
          - containerPort: 8501
          - containerPort: 8000  # Prometheus metrics
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: streamlit-service
  namespace: prod
spec:
  selector:
    app: streamlit
  type: ClusterIP
  ports:
    - name: ui
      port: 80
      targetPort: 8501
    - name: metrics
      port: 8000
      targetPort: 8000
